// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: artfs.proto

package artfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	manifest "infra/build/siso/toolsupport/artfsutil/proto/manifest"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCasFilesReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of files added.  Should be equal to the number of files
	// sent via the stream of FileManifests.
	Total         int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCasFilesReply) Reset() {
	*x = AddCasFilesReply{}
	mi := &file_artfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCasFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCasFilesReply) ProtoMessage() {}

func (x *AddCasFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_artfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCasFilesReply.ProtoReflect.Descriptor instead.
func (*AddCasFilesReply) Descriptor() ([]byte, []int) {
	return file_artfs_proto_rawDescGZIP(), []int{0}
}

func (x *AddCasFilesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_artfs_proto protoreflect.FileDescriptor

var file_artfs_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x72, 0x74, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61,
	0x72, 0x74, 0x66, 0x73, 0x1a, 0x17, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2f, 0x6d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a,
	0x10, 0x41, 0x64, 0x64, 0x43, 0x61, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0x4b, 0x0a, 0x05, 0x41, 0x72, 0x74, 0x66, 0x73,
	0x12, 0x42, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x43, 0x61, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12,
	0x16, 0x2e, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x72, 0x74, 0x66, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x43, 0x61, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x2f, 0x73, 0x69, 0x73, 0x6f, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x2f, 0x61, 0x72, 0x74, 0x66, 0x73, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x74, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_artfs_proto_rawDescOnce sync.Once
	file_artfs_proto_rawDescData = file_artfs_proto_rawDesc
)

func file_artfs_proto_rawDescGZIP() []byte {
	file_artfs_proto_rawDescOnce.Do(func() {
		file_artfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_artfs_proto_rawDescData)
	})
	return file_artfs_proto_rawDescData
}

var file_artfs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_artfs_proto_goTypes = []any{
	(*AddCasFilesReply)(nil),      // 0: artfs.AddCasFilesReply
	(*manifest.FileManifest)(nil), // 1: manifest.FileManifest
}
var file_artfs_proto_depIdxs = []int32{
	1, // 0: artfs.Artfs.AddCasFiles:input_type -> manifest.FileManifest
	0, // 1: artfs.Artfs.AddCasFiles:output_type -> artfs.AddCasFilesReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_artfs_proto_init() }
func file_artfs_proto_init() {
	if File_artfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_artfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artfs_proto_goTypes,
		DependencyIndexes: file_artfs_proto_depIdxs,
		MessageInfos:      file_artfs_proto_msgTypes,
	}.Build()
	File_artfs_proto = out.File
	file_artfs_proto_rawDesc = nil
	file_artfs_proto_goTypes = nil
	file_artfs_proto_depIdxs = nil
}
