// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: rusage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rusage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxRss int64 `protobuf:"varint,1,opt,name=max_rss,json=maxRss,proto3" json:"max_rss,omitempty"`
}

func (x *Rusage) Reset() {
	*x = Rusage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rusage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rusage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rusage) ProtoMessage() {}

func (x *Rusage) ProtoReflect() protoreflect.Message {
	mi := &file_rusage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rusage.ProtoReflect.Descriptor instead.
func (*Rusage) Descriptor() ([]byte, []int) {
	return file_rusage_proto_rawDescGZIP(), []int{0}
}

func (x *Rusage) GetMaxRss() int64 {
	if x != nil {
		return x.MaxRss
	}
	return 0
}

var File_rusage_proto protoreflect.FileDescriptor

var file_rusage_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x75, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x73, 0x69, 0x73, 0x6f, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x22, 0x21, 0x0a, 0x06,
	0x52, 0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x52, 0x73, 0x73, 0x42,
	0x20, 0x5a, 0x1e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x73,
	0x69, 0x73, 0x6f, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rusage_proto_rawDescOnce sync.Once
	file_rusage_proto_rawDescData = file_rusage_proto_rawDesc
)

func file_rusage_proto_rawDescGZIP() []byte {
	file_rusage_proto_rawDescOnce.Do(func() {
		file_rusage_proto_rawDescData = protoimpl.X.CompressGZIP(file_rusage_proto_rawDescData)
	})
	return file_rusage_proto_rawDescData
}

var file_rusage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rusage_proto_goTypes = []interface{}{
	(*Rusage)(nil), // 0: siso.execute.Rusage
}
var file_rusage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rusage_proto_init() }
func file_rusage_proto_init() {
	if File_rusage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rusage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rusage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rusage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rusage_proto_goTypes,
		DependencyIndexes: file_rusage_proto_depIdxs,
		MessageInfos:      file_rusage_proto_msgTypes,
	}.Build()
	File_rusage_proto = out.File
	file_rusage_proto_rawDesc = nil
	file_rusage_proto_goTypes = nil
	file_rusage_proto_depIdxs = nil
}
