#!/bin/sh
# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


# This script `go install`s the necessary tools that we use to generate *.pb.go
# files from *.proto files safely into its own directory.
#
# The rest of the arguments are the command to be run.
#
# It is intended to be used in `//go:generate` to be invoked
# by `go generate` to run protoc.

die() { 1>&2 printf '%s\n' "$@"; exit 1; }

mydir="$(realpath "$(dirname "$0")")"
test -d "$mydir" || die 'cannot find myself'

GOBIN="$mydir"/bin go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.5 || die 'cannot install'
GOBIN="$mydir"/bin go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1 || die 'cannot install'

exec env PATH="${mydir}/bin:${PATH}" "$@"
