#!/bin/sh
# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This script `go install`s the necessary tools that we use to generate *.pb.go
# files from *.proto files.
#
#  It is intended to be used in `//go:generate` to be invoked
#  by `go generate` to run protoc.
set -eu
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.2
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
